### ISSUE TITLE
Missing 'batch' variable in bootstrapped function?

### ISSUE THREAD

**Issue by porchard** [immunogenomics/SCENT#1]
Hi,

Congrats on the manuscript!

Should line 35 contain the 'batch' variable, as line 74 does...?

https://github.com/immunogenomics/SCENT/blob/ea82ea2cf2986e1f99611e3d7b8eb5be74017c29/SCENT.R#L35

**Comment by saorisakaue** [comment]
Dear @porchard ,

You are absolutely right! Thanks for catching this.
I now pushed the updated version at
https://github.com/immunogenomics/SCENT/commit/be82b5a359bee7cf6cab03951b6f480f0c7ecfad

Thanks,
Saori
