### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by mfansler** [immunogenomics/SCENT#10]
The `v1.0.1` tagged Release has `1.0.0` in the DESCRIPTION file. It is important to bump versions in the DESCRIPTION file, otherwise users capturing `sessionInfo()` cannot discern what version they are using.

**Comment by saorisakaue** [comment]
Hello Mervin,
Thanks so much for kindly letting me know! I just now updated it to the correct version number.
https://github.com/immunogenomics/SCENT/commit/33c6f9657b0f5cc67e61454b70d5e46e00519041
