### ISSUE TITLE
Is it possible to use SCENT for Bulk RNAseq data?

### ISSUE THREAD

**Issue by cparsania** [immunogenomics/SCENT#11]
Hi, 

I wonder if I can trick SCENT for bulk RNAseq data 

Cheers
Chirag.

**Comment by saorisakaue** [comment]
Hello,

No, our method is specifically designed for handling single-cell resolution discrete count data of ATAC-seq and RNA-seq. If you are interested in bulk ATAC-seq RNA-seq correlation, methods like EpiMap (Boix et al 2021) can be relevant.

Saori
