### ISSUE TITLE
How to predict gene expression after training the model?

### ISSUE THREAD

**Issue by lzj1769** [immunogenomics/SCENT#12]
Hi,

Given SCENT is a regression-based model, I would like to use it to predict the gene expression for some hold-out cells after training the model.

Is it possible to do so?

Thanks

**Comment by saorisakaue** [comment]
Hello,
As our regression model is univariate in nature (one peak - one gene pair at a time), I am not sure if the weighted peak accessibility by peak coefficients can accurately predict gene expression. We may need approaches like multivariate Ridge regression. Also, it is known that the accuracy of gene expression prediction is highly variable across genes, probably reflecting distinct gene regulatory mechanisms.

Saori
