### ISSUE TITLE
how to create custome bed file for gene-peak pair list

### ISSUE THREAD

**Issue by GGboy-Zzz** [immunogenomics/SCENT#14]
Tkans your for the interesting tool. I countered some blocker in using it.
As issue 6 mentioned, I want to create a gene-peak pair list for specific species, so I firstly need to create a custome bed file. Is this step about extracting the genomic coordinates of each gene and then extending 500 kb upstream and downstream, respectively?
best regards!

**Comment by saorisakaue** [comment]
Hello,
Yes, you are exactly right :) After obraining gtf file of the proper genomic build (consistent with the one for the ATAC regions and RNA read mapping), you can extract the definition of start & end position for the gene body, and extend it by 500 kb either side. You can specify this file for `genebed` argument in the `CreatePeakToGeneList` function.
Saori
