### ISSUE TITLE
Open dataset of SCENT peaks?

### ISSUE THREAD

**Issue by gabrielcerono** [immunogenomics/SCENT#5]
Hello everyone, great fan of this work! I have a question:

Is there any chance to get access to (already computed) a genome-wide scent peaks database? Does this dataset exist?

Bests, 

Gabriel.

**Comment by YichaoOU** [comment]
Hi,

Same request here. In your paper, you said, "We constructed 23 enhancer–gene maps with a total of 87,648 peak–gene links (false discovery rate (FDR) <10%)".

Can you please upload these 87K links here?

Thanks,
Yichao

**Comment by saorisakaue** [comment]
Hello Gabriel and Yichao,

Thank you for your interest in SCENT and so sorry for my delayed response! Now the linkages are available from the following dropbox link.

https://www.dropbox.com/scl/fo/g20tfnwkcuhib4a6z1wp4/ABYaK5s8bwTLnzrJ0KoZn48?rlkey=j1s5365gso53r2v2dsdynnsr2&st=5np1fq0a&dl=0

I hope this helps.
