### ISSUE TITLE
peak-gene bed: 500 kb windows for each gene

### ISSUE THREAD

**Issue by ofircohn** [immunogenomics/SCENT#6]
Hey!
Can you share your code for generating bed file that contains 500 kb windows for each gene

Thank you!

**Comment by saorisakaue** [comment]
Hello,

Apologies for my delayed response. I now added the bed file that includes regions for 500 kb windows for each gene here:
https://github.com/immunogenomics/SCENT/blob/main/data/GeneBody_500kb_margin.bed

I hope this helps!
Saori

**Comment by ofircohn** [comment]
Thanks! 
Since this is a data-specific file, can you share the code that generates these links?. I don't want to use Signac/ArchR gene-to-peaks methods.
