### ISSUE TITLE
Assumes all genes in GeneBody bed file are present in scRNA count matrix.

### ISSUE THREAD

**Issue by pazpark** [immunogenomics/SCENT#8]
Hi SCENT authors,

Thanks for releasing the tool. As a suggestion for future release, I've noticed that if you have a gene that is present in the GeneBody bed file but *not* in your scRNA matrix you'll get an error.
e.g. genebed_loc <- "./RData/Data/GeneBody_500kb_margin_chr.bed" 
I think this will happen often for users, so It would be nice if a check is added so that those genes missing can be skipped.

Thanks!
Chris

**Comment by saorisakaue** [comment]
Dear Chris,

Thanks so much for your interest in SCENT and your very helpful suggestion! I just fixed it as following:
https://github.com/immunogenomics/SCENT/commit/75071bdb738f7f3440106cb8a1cb82347c9a80aa

I hope this solves the issue, but please feel free to check it out and let me know something is still off.

Thanks,
Saori
